### PR TITLE
Project complete

### PR DESCRIPTION
**Pull request by Vgonma**
# Readme changes

- Add live demo link
- Add project presentation video link

# Other
I was merging my branch throughout the project so the main pull request can no longer be done. I am sorry for the inconvenience. Please let me know if there is a way to create a better pull request even after merging.
[This is a link to the full commits](https://github.com/Vgonma/conference-page/commits/main)

### CODE REVIEW

**Review by mgmediaweb — CHANGES_REQUESTED** [review]
Hi @Vgonma , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost3

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 
- Good job following the design. ✔️

## Required Changes ♻️

The PR that you send is not recommended, but I will make the changes indicating the corresponding lines:

- Kindly, I suggest that for accessibility every time you use an "IMG" you indicate an appropriate "ALT" to describe the content of that image.
[index.html line 61, 66, 71, 76, 81, 120]
[about.html line 75, 83, 109]

- Kindly, I suggest you remove the "</a>" tag, it is not performing any correct action.
[index.html line 109-113]
[about.html line 97-101]

- Kindly, I suggest you use the ARTICLE semantic tag, for repetitive content like this
[index.html line 59-85]
[main.js line 51]

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Vgonma** [comment]
Hi! Thanks for the comments @mgmediaweb. I do have some questions because I am not sure I understand this completely. 

> Kindly, I suggest you use the ARTICLE semantic tag, for repetitive content like this
> [index.html line 59-85]
> [main.js line 51]

I changed the `ul` to `article` on lines 59 - 85 
image
 
I don't understand where in main.js I should make the change. Should it be an article instead of a div? 
image

I was thinking maybe lines 96 and 97 of index.html should be the ones turned into articles
image

**Comment by mgmediaweb** [comment]
The idea is to replace all the UL/LI in this section with ARTICLES tags

**Comment by mgmediaweb** [comment]
in the main.js when you list the speakers instead of creating DIV tags, you should create ARTICLES tags

**Comment by Vgonma** [comment]
I am not sure if this is what you mean.
image
If it is, could you explain a little why it is better to use articles in this case?
@mgmediaweb

**Review by leonardodiasb — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @Vgonma 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - Professional-looking readme file. ✔️
 - Clear and descriptive Pull Request. ✔️
 - Clean and tidy code. ✔️
 - Good job following the design. ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
